import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import EPSButton from '../components/EPSButton'
import { useState, useEffect } from "react";
import { useContractRead, useAccount } from "wagmi";
import EPSAPI from '../contract/abi.json'
import { useRouter } from "next/router";


const Home: NextPage = () => {
  const jwt = require("jsonwebtoken");
  const { address, isConnecting, isDisconnected } = useAccount();
  const [hotWallet, setHotWallet] = useState<any[]>([]);
  const [decodedToken, setDecodedToken] = useState(null);
  const [error, setError] = useState<Error | null>(null);

  const router = useRouter();

  useEffect(() => {
    const token = router.query.token as string;
    if (token) {
      try {
        const decoded = jwt.verify(token, "secret");
        setDecodedToken(decoded);
      } catch (err) {
        setError(err as Error);
      }
    }
  }, [router.query]);

  useEffect(() => {
    if (address) {
      setHotWallet(address as any);
    }
  }, [address]);

  const { data, isError, isLoading } = useContractRead({
    address: "0x0000000000000aF8FE6E4DE40F4804C90fA8Ea8F",
    abi: EPSAPI,
    functionName: "hotToRecord",
    args: [address],
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} suppressHydrationWarning >
        <ConnectButton />
        <p>Hot Wallet: {hotWallet}</p>
        {data && (data as any).cold && (
          <p>EPS Connected Cold Wallet: {(data as any).cold}</p>
        )}
        <h1 className={styles.title}>Welcome to RainbowKit App 🪲🪲🪲🪲</h1>
        {decodedToken && (
          <p>Decoded Token: {JSON.stringify(decodedToken)}</p>
        )}
        {error && <p>Error: {error.message}</p>}
      </main>

      <footer className={styles.footer}>
        <a href="https://blossomdao.space" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at BlossomDAO
        </a>
      </footer>
    </div>
  );
};

export default Home;
